# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-16 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0002_auto_20180616_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
