# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-16 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0003_auto_20180616_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaner',
            name='city_id',
        ),
        migrations.AddField(
            model_name='cleaner',
            name='city_id',
            field=models.ManyToManyField(to='cleaning_app.Cities'),
        ),
    ]
