# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-16 07:51
from __future__ import unicode_literals

import cleaning_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0004_auto_20180616_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaner',
            name='city_id',
        ),
        migrations.AddField(
            model_name='cleaner',
            name='city',
            field=models.CharField(choices=[(1, b'Ahmedabad'), (2, b'Mumbai'), (3, b'Pune')], default=1, max_length=10, verbose_name=cleaning_app.models.Cities),
            preserve_default=False,
        ),
    ]
