# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-16 07:55
from __future__ import unicode_literals

import cleaning_app.models
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0005_auto_20180616_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='city',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, b'Ahmedabad'), (2, b'Mumbai'), (3, b'Pune')], max_length=10, verbose_name=cleaning_app.models.Cities),
        ),
    ]
