# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-16 08:14
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0007_auto_20180616_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='city',
            field=multiselectfield.db.fields.MultiSelectField(max_length=10),
        ),
    ]
