# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-16 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0008_auto_20180616_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaning_app.Customer'),
        ),
    ]
