# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0010_auto_20180616_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cleaning_app.Cities'),
            preserve_default=False,
        ),
    ]
